import { useState } from 'react'
import './App.css'
import KeriMannequin from './KeriMannequin'
import { defaultKeriLook, type KeriLook } from './keriAssets'

type Screen='home'|'design'|'wardrobe'|'colours'|'features'|'recipes'|'gallery'
type Tab='clothing'|'style'|'model'
const tops=[1,2,3,4,5], bottoms=[1,2,3], styles=[1,2,3,4,5,6]

function App(){
 const[screen,setScreen]=useState<Screen>('home'),[tab,setTab]=useState<Tab>('clothing'),[look,setLook]=useState<KeriLook>(defaultKeriLook)
 const patch=(p:Partial<KeriLook>)=>setLook(v=>({...v,...p}))
 const reset=()=>setLook(defaultKeriLook)
 const preview=(change:Partial<KeriLook>)=>({...look,...change})
 const Header=({back=false}:{back?:boolean})=><header className="top-bar">{back?<button className="home-button" onClick={()=>setScreen('home')}>← Studio</button>:<div className="brand"><span className="brand-icon">✦</span>Peyton's Fashion Studio</div>}<div className="designer">Designer Peyton</div><div className="star-count">⭐ 0</div></header>
 if(screen==='design')return <main className="app-shell"><Header back/><section className="designer-page"><div className="designer-challenge"><span>🎯</span><div><small>YOUR CHALLENGE</small><strong>Create a Look You Love!</strong></div><button>💡</button></div><div className="designer-workspace keri-workspace"><div className="designer-summary"><small>CURRENT LOOK</small><h2>Your Outfit</h2><p>Top {look.top} • Bottom {look.bottom}</p><p>Mix, match and make it yours ✨</p></div><div className="designer-mirror keri-mirror"><div className="mirror-shine"/><KeriMannequin look={look}/></div><div className="designer-tip"><span>♡</span><strong>Design • Create • Express</strong><p>There are no wrong designs.</p></div></div><div className="design-drawer"><div className="drawer-tabs"><button className={tab==='clothing'?'active':''} onClick={()=>setTab('clothing')}>👗 <span>Clothing</span></button><button className={tab==='style'?'active':''} onClick={()=>setTab('style')}>🎨 <span>Style</span></button><button className={tab==='model'?'active':''} onClick={()=>setTab('model')}>✨ <span>Model</span></button></div><div className="drawer-options keri-options">{tab==='clothing'&&<><div className="option-group visual-group"><b>TOPS</b><div className="visual-choice-row">{tops.map(n=><button key={n} className={`visual-choice ${look.top===n?'selected':''}`} onClick={()=>patch({top:n})}><span className="choice-preview"><KeriMannequin look={preview({top:n})}/></span><strong>Top {n}</strong>{look.top===n&&<i>✓</i>}</button>)}</div></div><div className="option-group visual-group"><b>BOTTOMS</b><div className="visual-choice-row">{bottoms.map(n=><button key={n} className={`visual-choice ${look.bottom===n?'selected':''}`} onClick={()=>patch({bottom:n})}><span className="choice-preview"><KeriMannequin look={preview({bottom:n})}/></span><strong>Bottom {n}</strong>{look.bottom===n&&<i>✓</i>}</button>)}</div></div></>}{tab==='style'&&<><div className="option-group"><b>TOP STYLE</b><div>{styles.map(n=><button key={n} className={look.topStyle===n?'selected':''} onClick={()=>patch({topStyle:n})}>{n}</button>)}</div></div><div className="option-group"><b>BOTTOM STYLE</b><div>{styles.map(n=><button key={n} className={look.bottomStyle===n?'selected':''} onClick={()=>patch({bottomStyle:n})}>{n}</button>)}</div></div></>}{tab==='model'&&<><div className="option-group"><b>SKIN</b><div>{[1,2,3,4,5].map(n=><button key={n} className={look.skin===n?'selected':''} onClick={()=>patch({skin:n})}>{n}</button>)}</div></div><div className="option-group"><b>HAIR</b><div>{[1,2,3,4,5].map(n=><button key={n} className={look.hairStyle===n?'selected':''} onClick={()=>patch({hairStyle:n})}>{n}</button>)}</div></div></>}</div></div><div className="designer-actions"><button className="reset-design" onClick={reset}>↻ Start Again</button><button className="finish-design">✓ Finish Design</button></div><p className="asset-credit">Keri character artwork by Konett • CC BY</p></section></main>
 if(screen!=='home')return <main className="app-shell"><Header/><section className="placeholder-page"><div className="placeholder-icon">✨</div><h1>{screen}</h1><p>We're building this part of the studio soon.</p><button className="back-button" onClick={()=>setScreen('home')}>← Back to Studio</button></section></main>
 return <main className="app-shell"><Header/><section className="studio"><div className="welcome"><p className="eyebrow">WELCOME, DESIGNER</p><h1>Your Fashion Studio</h1><p className="welcome-text">Create outfits, discover colours and build your own fashion collection.</p></div><div className="studio-floor"><button className="studio-area wardrobe-area" onClick={()=>setScreen('wardrobe')}><span className="area-icon">👗</span><span className="area-title">Wardrobe</span><span className="area-description">Your clothing collection</span></button><button className="studio-area colours-area" onClick={()=>setScreen('colours')}><span className="area-icon">🎨</span><span className="area-title">Colour Station</span><span className="area-description">Colours & mixing</span></button><button className="studio-area features-area" onClick={()=>setScreen('features')}><span className="area-icon">✨</span><span className="area-title">Feature Wall</span><span className="area-description">Details & decorations</span></button><button className="studio-area recipes-area" onClick={()=>setScreen('recipes')}><span className="area-icon">📖</span><span className="area-title">Recipe Book</span></button><button className="studio-area gallery-area" onClick={()=>setScreen('gallery')}><span className="area-icon">🖼️</span><span className="area-title">Fashion Gallery</span></button><button className="design-studio" onClick={()=>setScreen('design')}><div className="mirror keri-home-mirror"><div className="mirror-shine"/><KeriMannequin look={look}/></div><div className="design-studio-label"><span className="design-icon">🪞</span><div><strong>Design Studio</strong><small>Tap the model to start designing</small></div><span className="arrow">→</span></div></button></div><div className="first-challenge"><div className="challenge-icon">🎯</div><div className="challenge-copy"><span>YOUR FIRST CHALLENGE</span><strong>Create a Look You Love!</strong><p>No rules for your first design.</p></div><button className="challenge-button" onClick={()=>setScreen('design')}>Start Designing →</button></div></section><footer className="studio-footer"><span>👗 Create</span><span>🎨 Experiment</span><span>✨ Discover</span><span>💖 Have fun</span></footer></main>
}
export default App
