export type KeriLook = {
 skin:number
 hairStyle:number
 hairColour:number
 eyes:number
 eyeColour:number
 top:number
 topStyle:number
 topSet:number
 bottom:number
 bottomStyle:number
 bottomSet:number
 dress:number
 dressStyle:number
 jacket:number
 jacketStyle:number
 jacketSet:number
 shoes:number
 shoesStyle:number
 shoesSet:number
 necklace:number
 necklaceSet:number
 earrings:number
 earringsSet:number
 bracelet:number
}

export const defaultKeriLook:KeriLook={
 skin:1,
 hairStyle:1,
 hairColour:1,
 eyes:1,
 eyeColour:1,
 top:1,
 topStyle:1,
 topSet:1,
 bottom:1,
 bottomStyle:1,
 bottomSet:1,
 dress:0,
 dressStyle:1,
 jacket:0,
 jacketStyle:1,
 jacketSet:1,
 shoes:1,
 shoesStyle:1,
 shoesSet:1,
 necklace:0,
 necklaceSet:1,
 earrings:0,
 earringsSet:1,
 bracelet:0,
}
